### ISSUE TITLE
Add ability to ignore specific routes

### ISSUE THREAD

**Issue by Csucsi92** [weespin/SeaBot#14]
hi!
i have question!
would it be possible to choose which ship to send to? etc: 1 hour coin, 15min coin etc? i set autoship mode and bot send my ships random routes,but i wanna choose :) thank you

**Comment by weespin** [comment]
Yeah, I can add it. But routes are not random. Bot is literally calculating route using materialmultiplier/time (only loot) or materialmultiplier/sailors   (save sailors). If bot is sending ships to "random" points - your ship have less than required amount of sailors and bot will find a spot with less required sailors but still efficient.

**Comment by Csucsi92** [comment]
i understand thank you :)
