### ISSUE TITLE
Ресурсы через телеграмм

### ISSUE THREAD

**Issue by Shmurdyaka** [weespin/SeaBot#21]
Было бы не плохо иметь возможность через телеграмм посмотреть сколько ресурсов есть, сколько в складе ресурсов, какие корабли где. 
А то для этого приходится останавливать бот и запускать игру.

**Comment by weespin** [comment]
Добавлю 
P.S. Не обязательно выключать бота чтобы запустить игру 😄

**Comment by weespin** [comment]
Ресурсы можно и так посмотреть нажав в телеграм боте, "инвентарь"

**Comment by weespin** [comment]
Добавил корабли в телеграм бота
