### ISSUE TITLE
Ошибочный выбор пункта.

### ISSUE THREAD

**Issue by Louren325** [weespin/SeaBot#22]
В 0.8.8 версии при таких настройках https://i.imgur.com/lnMAcvE.png бот стал отправлять корабли в Ривьеру https://i.imgur.com/C7LFnul.png, хотя в 0.8.7.11 корректно посылает корабли в Городок (https://i.imgur.com/81XlEJx.png https://i.imgur.com/NXgmIwV.png) Рейты х255 против х13.
Нужно ли прикладывать отладочный файл?

**Comment by weespin** [comment]
Скорее всего я перепутал местами только лут и сохранять моряков

**Comment by weespin** [comment]
Исправлено в 0.8.8.1
