### ISSUE TITLE
Настройки сна бота

### ISSUE THREAD

**Issue by starikc** [weespin/SeaBot#26]
Привет!
В настройках сна бота по умолчанию стоит что он будет спать 25 минут, если меняю значение (допустим выставляю 5 минут), то он спит всё равно 25 минут, и при перезаходе в приложение слетает выставленное значение и ставится опять по умолчанию 25 минут. Настройка "спать каждые" вроде бы работает корректно.

**Comment by weespin** [comment]
Fixed
