### ISSUE TITLE
SeaBot DEBUG GUI missing from github

### ISSUE THREAD

**Issue by willyaranda** [weespin/SeaBot#29]
**Describe the bug**
SeaBot DEBUG from GUI is missing in github.

**To Reproduce**
1. Clone the repo
2. Try to compile
3. Error!

**Expected behavior**
A nice bot for SeaPort compiled from sources (master)

**Comment by weespin** [comment]
Fixed https://github.com/weespin/SeaBot/commit/2f62164e0ccd848c440867c91728df8c3b3db80a
