### ISSUE TITLE
0.7

### ISSUE THREAD

**Issue by Ampolyros** [weespin/SeaBot#3]
Приложение запускается, но при старте вываливается с ошибкой. На оф сайте игры теперь невозможно получить токен.

**Comment by weespin** [comment]
Удали все куки/logout и заходи в свой аккаунт, куки с токеном должны появиться

**Comment by Ampolyros** [comment]
Удаление куков по фильтру pixel... помогло, приложение заработало. Спасибо.
Разработка мобильного бота планируется? Подписан на канал в телеге, где было сообщение об управление ботом через канал телеги.

**Comment by weespin** [comment]
Надеюсь всё будет, я сейчас работаю с кораблями :D
