### ISSUE TITLE
Очистка логов и статистики

### ISSUE THREAD

**Issue by Shmurdyaka** [weespin/SeaBot#33]
Заметил что за несколько дней эксплуатации бота, папка с ним увеличилась в объеме до 140МБ.

Увеличение объема связано со скопившимися логами, кешем, статистикой и дампами.

Считаю что было бы не плохо в настройках сделать "раздел" с настройками очистки кеша, логов и статистики. На выбор по нажатию на кнопку или же по расписанию.

**Comment by weespin** [comment]
Скорее всего сделаю "хранить N-колво последних логов"
