### ISSUE TITLE
server token

### ISSUE THREAD

**Issue by LordSweet** [weespin/SeaBot#39]
today i cant see server token anymore in EditThisCookie

2019-03-04 10:49:33.846 [FATAL]   CANT LOGIN!

**Comment by LordSweet** [comment]
now i can see it back.i dont know how but it appear again 30min later

2019-03-04 11:14:50.556 [INFO]    Successfully logged in! Session ID =

**Comment by DarkwellZ** [comment]
After your cookie has expired and you need to login, sometimes restarting my browser helps EditThisCookie to display my token again.

**Comment by weespin** [comment]
https://github.com/weespin/SeaBot/wiki/Troubleshooting
